"""authentication for organization

Revision ID: 1e01c3abd0b7
Revises: ee82880ea535
Create Date: 2025-05-13 22:15:45.997178

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1e01c3abd0b7'
down_revision: Union[str, None] = 'ee82880ea535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('hashed_password', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'organizations', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_column('organizations', 'hashed_password')
    # ### end Alembic commands ###
