"""Create hnsw index for embedding table

Revision ID: 7b83852be5e1
Revises: dc209b933385
Create Date: 2025-06-15 20:41:39.665803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b83852be5e1'
down_revision: Union[str, None] = 'dc209b933385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_embeddings_embedding', table_name='embeddings', postgresql_using='ivfflat')
    op.create_index('ix_embeddings_vector', 'embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '200'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_embeddings_vector', table_name='embeddings', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '200'})
    op.create_index('ix_embeddings_embedding', 'embeddings', ['embedding'], unique=False, postgresql_using='ivfflat')
    # ### end Alembic commands ###
