"""add client_id to chat_session

Revision ID: dc209b933385
Revises: 3d80fbd44f2f
Create Date: 2025-05-17 19:28:51.466172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc209b933385'
down_revision: Union[str, None] = '3d80fbd44f2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_users', sa.Column('client_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'external_users', 'app_clients', ['client_id'], ['client_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'external_users', type_='foreignkey')
    op.drop_column('external_users', 'client_id')
    # ### end Alembic commands ###
