"""add collection ids to app client

Revision ID: ee82880ea535
Revises: 91d63f70fdd5
Create Date: 2025-05-13 08:58:02.970239

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ee82880ea535'
down_revision: Union[str, None] = '91d63f70fdd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_clients',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('client_secret', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('scopes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('external_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_user', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_client_collection',
    sa.Column('app_client_id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['app_client_id'], ['app_clients.client_id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('app_client_id', 'collection_id')
    )
    op.add_column('chat_sessions', sa.Column('external_user_id', sa.UUID(), nullable=False))
    op.add_column('chat_sessions', sa.Column('client_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'chat_sessions', 'app_clients', ['client_id'], ['client_id'])
    op.create_foreign_key(None, 'chat_sessions', 'external_users', ['external_user_id'], ['id'])
    op.drop_column('chat_sessions', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'client_id')
    op.drop_column('chat_sessions', 'external_user_id')
    op.drop_table('app_client_collection')
    op.drop_table('external_users')
    op.drop_table('app_clients')
    # ### end Alembic commands ###
