"""remove is-default in collection table

Revision ID: 3c602bbce4e0
Revises: 1e01c3abd0b7
Create Date: 2025-05-15 20:46:47.006823

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3c602bbce4e0'
down_revision: Union[str, None] = '1e01c3abd0b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'is_default')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
