"""chat session and collection

Revision ID: a98fa83ba6b2
Revises: 2ac9890ff864
Create Date: 2025-05-15 21:53:42.645850

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a98fa83ba6b2'
down_revision: Union[str, None] = '2ac9890ff864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_session_collection',
    sa.Column('chat_session_id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('chat_session_id', 'collection_id')
    )
    op.drop_constraint('chat_sessions_collection_id_fkey', 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'collection_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('chat_sessions_collection_id_fkey', 'chat_sessions', 'collections', ['collection_id'], ['id'])
    op.drop_table('chat_session_collection')
    # ### end Alembic commands ###
